spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      file: compose.yaml
      profiles:
        active: dev
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /docs/swagger
management:
  endpoint:
    health:
      show-details: always
      show-components: always
